server:
  port: ${PORT:8082}

spring:
  application:
    name: objetos-service
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/vecinosdb}
    username: ${DB_USER:vecinosuser}
    password: ${DB_PASSWORD:vecinospass}
    properties:
      sslMode: ${SSL_MODE:ALLOW}

management:
  endpoints:
    web:
      exposure:
        include: health,info
